# frozen_string_literal: true

require 'cucumber'
require 'cucumber/rake/task'
require 'rake'

cmd_features_cucumber = 'cucumber features/cucumber ' \
                        '--require features ' \
                        '--format pretty'

namespace :features do
  desc 'Run cucumber behavior tests'
  task :cucumber, :tags do |_, args|
    tags = args[:tags] ? "--tags '#{args[:tags]}'" : ''
    @commands << "#{cmd_features_cucumber} #{tags}"
  end
end
