# frozen_string_literal: true

namespace :project do
  desc 'Build takeltau cli ruby gem'
  task prod: %w[gem:signin
                rubylint
                test
                features
                doc:clean
                doc:build
                doc:commit
                gem:clean
                gem:build
                gem:move
                git:tag
                gem:push]
end
