AllCops:
  NewCops: enable
Gemspec/DevelopmentDependencies:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 150
Metrics/ModuleLength:
  Max: 150
