AllCops:
  NewCops: enable
Gemspec/DevelopmentDependencies:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/MethodLength:
  Max: 20
Metrics/ClassLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Naming/PredicateMethod:
  Enabled: false
