version = File.read "#{File.dirname(__FILE__)}/../../lib/takelage/version"
version.chomp!

# for SOURCE_DATE_EPOCH see https://reproducible-builds.org
cmd_gem_build = 'SOURCE_DATE_EPOCH=1575849432 gem build takelage'
cmd_gem_clean = "rm -f *.gem gem/takelage-#{version}.gem"
cmd_gem_move = 'mkdir -p gem && mv *.gem gem'
cmd_gem_push = "gem push gem/takelage-#{version}.gem"

namespace :gem do
  desc 'Build takelage gem'
  task :build do
    $commands << cmd_gem_build
  end

  desc 'Clean takelage gem'
  task :clean do
    $commands << cmd_gem_clean
  end

  desc 'Move takelage gem'
  task :move do
    $commands << cmd_gem_move
  end

  desc 'Push takelage gem to rubygems.org'
  task :push do
    $commands << cmd_gem_push
  end
end
