# frozen_string_literal: true

version = File.read "#{File.dirname(__FILE__)}/../../lib/takeltau/version"
version.chomp!

# for SOURCE_DATE_EPOCH see https://reproducible-builds.org
cmd_gem_build = 'SOURCE_DATE_EPOCH=1575849432 gem build takeltau'
cmd_gem_clean = "rm -f *.gem gem/takeltau-#{version}.gem"
cmd_gem_move = 'mkdir -p gem && mv *.gem gem'
cmd_gem_push = "gem push gem/takeltau-#{version}.gem"
cmd_gem_signin = 'gem signin'

namespace :gem do
  desc 'Build takeltau gem'
  task :build do
    @commands << cmd_gem_build
  end

  desc 'Clean takeltau gem'
  task :clean do
    @commands << cmd_gem_clean
  end

  desc 'Move takeltau gem'
  task :move do
    @commands << cmd_gem_move
  end

  desc 'Push takeltau gem to rubygems.org'
  task :push do
    @commands << cmd_gem_push
  end

  desc 'Sign in to rubygems.org'
  task :signin do
    @commands << cmd_gem_signin
  end
end
