# frozen_string_literal: true

require 'rake'

cmd_doc_build = 'yardoc --template-path ./yard'
cmd_doc_clean = 'rm -fr doc/*'
cmd_doc_commit = 'tau git check clean || ' \
  '(git add doc && git commit -m "Update docs")'

namespace :doc do
  desc 'Build takeltau doc'
  task :build do
    @commands << cmd_doc_build
  end

  desc 'Clean takeltau doc'
  task :clean do
    @commands << cmd_doc_clean
  end

  desc 'Commit takeltau doc'
  task :commit do
    @commands << cmd_doc_commit
  end
end
