name: Test project

on:
  schedule: # run daily at 1 pm CET
    - cron:  '0 2 * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  test-project:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install mutagen
        run: |
          wget -O /tmp/mutagen.tar.gz https://github.com/mutagen-io/mutagen/releases/download/v0.11.8/mutagen_linux_amd64_v0.11.8.tar.gz
          sudo tar xvfz /tmp/mutagen.tar.gz -C /usr/local/bin

      - name: Add host.docker.internal to /etc/hosts
        run: echo "127.0.0.1 host.docker.internal" | sudo tee --append /etc/hosts

      - name: Set up ruby
        uses: ruby/setup-ruby@v1.61.1
        with:
          ruby-version: 2.7

      - name: Install tau
        run: gem install takeltau

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass" >> $HOME/.takelage.yml
          echo "docker_run_options: --cap-add=NET_ADMIN" >> $HOME/.takelage.yml
          echo "docker_repo: takelbeta" >> $HOME/.takelage.yml

      - name: Configure docker daemon
        run: |
          echo '{ "cgroup-parent": "/actions_job", "insecure-registries": [ "host.docker.internal:5005" ] }' > /tmp/daemon.json
          sudo mv /tmp/daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker.service

      - name: Pull takelage image
        run: tau update

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

      - name: Run unit tests
        run: tau docker container command "rake test"

      - name: Run cucumber features
        run: tau docker container command "rake features"
