name: test takeltau

on:
  schedule: # run daily at 1 pm CET
    - cron:  '0 2 * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Configure gnupg and ssh on the host
        run: |
          mkdir $HOME/.ssh
          echo "AddKeysToAgent yes" >> $HOME/.ssh/config
          mkdir $HOME/.gnupg
          echo "batch" >> $HOME/.gnupg/gpg-agent.conf
          echo "enable-ssh-support" >> $HOME/.gnupg/gpg-agent.conf

      - name: Add host.docker.internal to /etc/hosts
        run: echo "127.0.0.1 host.docker.internal" | sudo tee --append /etc/hosts

      - name: Set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby

      - name: Install tau
        run: gem install takeltau

      - name: Configure tau
        run: |
          echo "docker_entrypoint_options: --no-git --no-gopass" >> $HOME/.takelage.yml
          echo "docker_run_options: --cap-add=NET_ADMIN" >> $HOME/.takelage.yml
          echo "docker_repo: takelbuild" >> $HOME/.takelage.yml
          echo "docker_tag: latest-amd64" >> $HOME/.takelage.yml
          cat $HOME/.takelage.yml

      - name: Configure docker daemon
        run: |
          echo '{ "insecure-registries": [ "host.docker.internal:5005" ] }' > /tmp/daemon.json
          sudo mv /tmp/daemon.json /etc/docker/daemon.json
          sudo systemctl restart docker.service

      - name: Pull takelage image
        run: tau update

      - name: Read mutagen version
        run: |
          MUTAGEN=$(docker inspect --format '{{ index .Config.Labels "mutagen" }}' takelwerk/takelbuild:latest-amd64)
          echo "MUTAGEN=$MUTAGEN" >> "$GITHUB_ENV"

      - name: Install mutagen
        run: |
          MUTAGEN_FILE=https://github.com/mutagen-io/mutagen/releases/download/v${{ env.MUTAGEN }}/mutagen_linux_amd64_v${{ env.MUTAGEN }}.tar.gz
          wget --header="Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -O /tmp/mutagen.tar.gz $MUTAGEN_FILE
          sudo tar xvfz /tmp/mutagen.tar.gz -C /usr/local/bin
          mutagen daemon start

      - name: Start an instance of takelage
        run: tau docker container daemon

      - name: Lint ruby
        run: tau docker container command "rake rubylint"

      - name: Run unit tests
        run: tau docker container command "rake test"

      - name: Run cucumber features
        run: tau docker container command "SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket) rake features"
